src/main/java/com/przychodnia/rejestracja/jsf/ApplicationBean.java
package com.przychodnia.rejestracja.jsf;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import org.primefaces.model.menu.DefaultMenuItem;
import org.primefaces.model.menu.DefaultMenuModel;
import org.primefaces.model.menu.DefaultSubMenu;
import org.primefaces.model.menu.MenuModel;
import org.springframework.beans.factory.annotation.Configurable;

import com.przychodnia.rejestracja.jsf.util.Literals;

@Configurable
@ManagedBean
@RequestScoped
public class ApplicationBean {

    public static String getColumnName(String column) {
        if (column == null || column.length() == 0) {
            return column;
        }
        final Pattern p = Pattern.compile("[A-Z][^A-Z]*");
        final Matcher m = p.matcher(Character.toUpperCase(column.charAt(0)) + column.substring(1));
        final StringBuilder builder = new StringBuilder();
        while (m.find()) {
            builder.append(m.group()).append(" ");
        }
        return builder.toString().trim();
    }

    private MenuModel menuModel;

	@PostConstruct
    public void init() {
        
        menuModel = new DefaultMenuModel();
     
      //Mail submenu
        DefaultSubMenu messagesMenu = new DefaultSubMenu();
        DefaultMenuItem item;
        
        item = new DefaultMenuItem();
        item.setId("createEmailMenuItem");
        item.setValue(Literals.CREATE);
        item.setCommand("#{mailBean.displayCreateDialog}");
        item.setIcon("ui-icon ui-icon-document");
        item.setAjax(false);
        item.setAsync(false);
        item.setUpdate(":dataForm:data");
        messagesMenu.addElement(item);
        
        messagesMenu.setId("mailSubmenu");
        messagesMenu.setLabel(Literals.Mail);
        item = new DefaultMenuItem(Literals.SHOW);
        item.setId("mailMenuItem");
        item.setCommand("#{mailBean.displayList}");
        item.setIcon("ui-icon ui-icon-document");
        messagesMenu.addElement(item);
        menuModel.addElement(messagesMenu);
        
        //Bhours submenu
        DefaultSubMenu bhoursMenu = new DefaultSubMenu();
        
        bhoursMenu.setId("officeHoursSubmenu");
        bhoursMenu.setLabel(Literals.OFFICE_HOURS_LABEL);
        item = new DefaultMenuItem(Literals.SHOW);
        item.setId("createOfficeHoursMenuItem");
        item.setCommand("#{bhoursBean.displayList}");
        item.setIcon("ui-icon ui-icon-document");
        bhoursMenu.addElement(item);
        menuModel.addElement(bhoursMenu);
        
        //Schedule submenu
        DefaultSubMenu scheduleMenu = new DefaultSubMenu();
        
        scheduleMenu.setId("scheduleSubmenu");
        scheduleMenu.setLabel(Literals.SCHEDULE_LABEL);
        item = new DefaultMenuItem(Literals.SCHEDULE_SHOW);
        item.setId("createScheduleMenuItem");
        item.setCommand(Literals.SCHEDULE);
        item.setIcon("ui-icon ui-icon-document");
        scheduleMenu.addElement(item);
        
        item = new DefaultMenuItem();
        item.setId("listAppointmentMenuItem");
        item.setValue(Literals.APOINTMENTS_SHOW);
        item.setCommand("#{appointmentBean.displayList}");
        item.setIcon("ui-icon ui-icon-folder-open");
        item.setAjax(false);
        item.setAsync(false);
        item.setUpdate(":dataForm:data");
        
        scheduleMenu.addElement(item);
        menuModel.addElement(scheduleMenu);
        
        //Doctor submenu
        DefaultSubMenu doctorMenu = new DefaultSubMenu();
        doctorMenu.setId("doctorSubmenu");
        doctorMenu.setLabel(Literals.DOCTOR_LABEL);
        
        item = new DefaultMenuItem();
        item.setId("createDoctorMenuItem");
        item.setValue(Literals.CREATE);
        item.setCommand("#{doctorBean.displayCreateDialog}");
        item.setIcon("ui-icon ui-icon-document");
        item.setAjax(false);
        item.setAsync(false);
        item.setUpdate(":dataForm:data");
        doctorMenu.addElement(item);
        
        item = new DefaultMenuItem();
        item.setId("listDoctorMenuItem");
        item.setValue(Literals.SHOW);
        item.setCommand("#{doctorBean.displayList}");
        item.setIcon("ui-icon ui-icon-folder-open");
        item.setAjax(false);
        item.setAsync(false);
        item.setUpdate(":dataForm:data");
        doctorMenu.addElement(item);
        
        menuModel.addElement(doctorMenu);
        
        //Patient submenu
        DefaultSubMenu patientMenu = new DefaultSubMenu();
        patientMenu.setId("personSubmenu");
        patientMenu.setLabel(Literals.PATIENT_LABEL);
        
        item = new DefaultMenuItem();
        item.setId("createPersonMenuItem");
        item.setValue(Literals.CREATE);
        item.setCommand("#{personBean.displayCreateDialog}");
        item.setIcon("ui-icon ui-icon-document");
        item.setAjax(false);
        item.setAsync(false);
        item.setUpdate(":dataForm:data");
        patientMenu.addElement(item);
        
        item = new DefaultMenuItem();
        item.setId("listPersonMenuItem");
        item.setValue(Literals.SHOW);
        item.setCommand("#{personBean.displayList}");
        item.setIcon("ui-icon ui-icon-folder-open");
        item.setAjax(false);
        item.setAsync(false);
        item.setUpdate(":dataForm:data");
        patientMenu.addElement(item);
        
        menuModel.addElement(patientMenu);
        
    }

	public MenuModel getMenuModel() {
        return menuModel;
    }

	public String getAppName() {
        return "Rejestracja";
    }
}

src/main/java/com/przychodnia/rejestracja/jsf/AppointmentBean.java
package com.przychodnia.rejestracja.jsf;

import com.przychodnia.rejestracja.domain.Appointment;
import com.przychodnia.rejestracja.domain.Doctor;
import com.przychodnia.rejestracja.domain.Person;
import com.przychodnia.rejestracja.integration.EmailManager;
import com.przychodnia.rejestracja.jsf.util.Literals;
import com.przychodnia.rejestracja.jsf.util.MessageFactory;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import org.primefaces.context.RequestContext;
import org.primefaces.event.CloseEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Configurable;

@Configurable
@ManagedBean(name = "appointmentBean")
@SessionScoped
public class AppointmentBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	
	private Appointment appointment;

	private List<Appointment> allAppointments;
	private List<Appointment> filteredAppointments;
	private boolean dataVisible = false;

	private boolean createDialogVisible = false;

	@Autowired
	private EmailManager emailManager;;
	
	@PostConstruct
	public void init() {
	}

	public void sendMail() {
		emailManager.addRemindAppointmentMail(getAppointment());
	}

	public List<Appointment> getAllAppointments() {
		return allAppointments;
	}

	public void setAllAppointments(List<Appointment> allAppointments) {
		this.allAppointments = allAppointments;
	}

	public List<Appointment> getFilteredAppointments() {
		return filteredAppointments;
	}

	public void setFilteredAppointments(List<Appointment> filteredAppointments) {
		this.filteredAppointments = filteredAppointments;
	}

	public String findAllAppointments() {
		allAppointments = Appointment.findAllAppointments();
		dataVisible = !allAppointments.isEmpty();
		return null;
	}

	public boolean isDataVisible() {
		return dataVisible;
	}

	public void setDataVisible(boolean dataVisible) {
		this.dataVisible = dataVisible;
	}

	public Appointment getAppointment() {
		if (appointment == null) {
			appointment = new Appointment();
		}
		return appointment;
	}

	public void setAppointment(Appointment appointment) {
		this.appointment = appointment;
	}

	public List<Doctor> completeDoctor(String query) {
		List<Doctor> suggestions = new ArrayList<Doctor>();
		for (Doctor doctor : Doctor.findAllDoctors()) {
			String doctorStr = String.valueOf(doctor.getSurname() + " "
					+ doctor.getFirstName() + " " + doctor.getProfession());
			if (doctorStr.toLowerCase().startsWith(query.toLowerCase())) {
				suggestions.add(doctor);
			}
		}
		return suggestions;
	}

	public List<Person> completePatient(String query) {
		List<Person> suggestions = new ArrayList<Person>();
		for (Person person : Person.findAllPeople()) {
			String personStr = String.valueOf(person.getSurname() + " "
					+ person.getFirstName() + " " + person.getFatherName()
					+ " " + person.getBirthDate());
			if (personStr.toLowerCase().startsWith(query.toLowerCase())) {
				suggestions.add(person);
			}
		}
		return suggestions;
	}

	public String onEdit() {
		return null;
	}

	public boolean isCreateDialogVisible() {
		return createDialogVisible;
	}

	public void setCreateDialogVisible(boolean createDialogVisible) {
		this.createDialogVisible = createDialogVisible;
	}

	public String displayList() {
		createDialogVisible = false;
		findAllAppointments();
		return "appointment";
	}

	public String displayCreateDialog() {
		appointment = new Appointment();
		createDialogVisible = true;
		return "appointment";
	}

	public String persist() {
		if (appointment.isDayCorrect()) {
			if (appointment.getId() != null) {
				appointment.merge();
				emailManager.addCreateAppointmentMail(appointment);
			} else {
				appointment.persist();
				emailManager.addUpdateAppointmentMail(appointment);
			}
			RequestContext context = RequestContext.getCurrentInstance();
			context.execute("createDialogWidget.hide()");
			context.execute("editDialogWidget.hide()");
			
			FacesMessage facesMessage = MessageFactory.getMessage(
					"appointment_sucesfully_added",  appointment.getAppointmentStartDate());
			FacesContext.getCurrentInstance().addMessage(null, facesMessage);
		} else {
			FacesMessage facesMessage = MessageFactory.getMessage(
					"appointment_not_added",  appointment.getAppointmentStartDate());
			FacesContext.getCurrentInstance().addMessage(null, facesMessage);
		}
		reset();
		return findAllAppointments();
	}

	public String delete() {
		appointment.remove();

		FacesMessage facesMessage = MessageFactory.getMessage(
				"message_successfully_deleted", Literals.APPOINTMENT_LABEL);
		FacesContext.getCurrentInstance().addMessage(null, facesMessage);

		reset();
		return findAllAppointments();
	}

	public void reset() {
		appointment = null;
		createDialogVisible = false;
	}

	public void handleDialogClose(CloseEvent event) {
		reset();
	}
}

src/main/java/com/przychodnia/rejestracja/jsf/BhoursBean.java
package com.przychodnia.rejestracja.jsf;

import com.przychodnia.rejestracja.domain.Bhours;
import com.przychodnia.rejestracja.domain.Doctor;
import com.przychodnia.rejestracja.jsf.util.Day;
import com.przychodnia.rejestracja.jsf.util.Literals;
import com.przychodnia.rejestracja.jsf.util.MessageFactory;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import org.primefaces.event.CloseEvent;
import org.primefaces.event.SelectEvent;
import org.primefaces.event.UnselectEvent;
import org.springframework.beans.factory.annotation.Configurable;

@ManagedBean(name = "bhoursBean")
@SessionScoped
@Configurable
public class BhoursBean implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 7487846715965801488L;
	private String name = "bhours";
	private String dayOfWeekString;
	private Bhours bhours;
	private List<Bhours> allBhourses;
	private List<Bhours> filteredBhourses;
	private List<Bhours> filteredBhoursesForDoctor;
	private Doctor selectedDoctor;
	private boolean dataVisible = false;
	private boolean createDialogVisible = false;

	@PostConstruct
	public void init() {
		findAllBhourses();
		DoctorBean.findAllDoctors();
		bhours = new Bhours();
	}

	// Wyswietlanie
	public String findAllBhourses() {
		allBhourses = Bhours.findAllBhourses();
		dataVisible = !allBhourses.isEmpty();
		return null;
	}
	
	public String findBhoursForDoctor(Doctor doctor) {
		filteredBhoursesForDoctor = Bhours.findBhoursesByDoctor(doctor);
		return null;
	}

	//Obsluga listenrow
	  public void onRowSelect(SelectEvent event) {
		  findBhoursForDoctor(getSelectedDoctor());
		  
		  FacesMessage facesMessage = MessageFactory.getMessage("doctor_selected",((Doctor) event.getObject()).getSurname());		
			FacesContext.getCurrentInstance().addMessage(null, facesMessage);
	    }
	 
	    public void onRowUnselect(UnselectEvent event) {
	    	FacesMessage facesMessage = MessageFactory.getMessage("doctor_unselected",((Doctor) event.getObject()).getSurname());		
			FacesContext.getCurrentInstance().addMessage(null, facesMessage);
	    }
	    
	public String displayList() {
		createDialogVisible = false;
		findAllBhourses();
		return "bhours";
	}

	public String displayOfficeHours() {
		return "bhours";
	}

	public String displayCreateDialog() {
		bhours = new Bhours();
		createDialogVisible = true;
		return "bhours";
	}

	// Zapisywanie
	public void persist() {
		String message = "";
		if (!bhours.isBhoursTaken()) {
			
		if (bhours.getId() != null) {
				bhours.merge();
				message = "message_successfully_updated";
			} else {
				bhours.persist();
				message = "message_successfully_created";
			}
			FacesMessage facesMessage = MessageFactory.getMessage(message,
					Literals.BHOURS);
			FacesContext.getCurrentInstance().addMessage(null, facesMessage);
			findBhoursForDoctor(bhours.getDoctor());
			reset();
		}
		else {
			
			FacesMessage facesMessage = MessageFactory.getMessage("bhours_notsucesfully_added_reason");		
			FacesContext.getCurrentInstance().addMessage(null, facesMessage);
			
		findBhoursForDoctor(bhours.getDoctor());
		reset();
		}
	}

	// Usuwanie
	public void delete() {
		bhours.remove();
		FacesMessage facesMessage = MessageFactory
				.getMessage("message_successfully_deleted");
		FacesContext.getCurrentInstance().addMessage(null, facesMessage);
		findBhoursForDoctor(bhours.getDoctor());
		reset();
	}

	// Util
	public void reset() {
		bhours = null;
		createDialogVisible = false;
	}

	public void handleDialogClose(CloseEvent event) {
		reset();
	}

	// Gettery i settery
	public boolean isDataVisible() {
		return dataVisible;
	}

	public void setDataVisible(boolean dataVisible) {
		this.dataVisible = dataVisible;
	}

	public Bhours getBhours() {
		if (bhours == null) {
			bhours = new Bhours();
		}
		return bhours;
	}

	public void setBhours(Bhours bhours) {
		this.bhours = bhours;
	}

	public Day[] getDays() {
		return Day.values();
	}

	public String onEdit() {
		return null;
	}

	public boolean isCreateDialogVisible() {
		return createDialogVisible;
	}

	public void setCreateDialogVisible(boolean createDialogVisible) {
		this.createDialogVisible = createDialogVisible;
	}

	public String getName() {
		return name;
	}

	public Doctor getSelectedDoctor() {
				return selectedDoctor;
	}

	public void setSelectedDoctor(Doctor selectedDoctor) {
		this.selectedDoctor = selectedDoctor;
	}

	public List<Bhours> getAllBhourses() {
		return allBhourses;
	}

	public void setAllBhourses(List<Bhours> allBhourses) {
		this.allBhourses = allBhourses;
	}

	public List<Bhours> getFilteredBhourses() {
		return filteredBhourses;
	}

	public void setFilteredBhourses(List<Bhours> filteredBhourses) {
		this.filteredBhourses = filteredBhourses;
	}

	public List<Bhours> getFilteredBhoursesForDoctor() {
		return filteredBhoursesForDoctor;
	}

	public void setFilteredBhoursesForDoctor(List<Bhours> filteredBhoursesForDoctor) {
		this.filteredBhoursesForDoctor = filteredBhoursesForDoctor;
	}

	public String getDayOfWeekString() {
		return dayOfWeekString;
	}

	public void setDayOfWeekString(String dayOfWeekString) {
		this.dayOfWeekString = dayOfWeekString;
	}
}

src/main/webapp/pages/secure/appointment.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"> <ui:composition
	template="../../templates/layout.xhtml">
	<ui:define name="content">
		<h:form prependId="false" id="growlForm">
			<p:growl id="growl" showDetail="true" escape="false"
				globalOnly="true" />
		</h:form>
		<h:form prependId="false" id="dataForm">
			<p:panel id="data" toggleable="true" toggleSpeed="250">
				<f:facet name="header">
					<h:outputText value="#{messages.label_appointment}" />
				</f:facet>
				<h:outputFormat id="noRecordsFound"
					value="#{messages.label_no_records_found}"
					rendered="#{!appointmentBean.dataVisible}">
					<f:param value="#{messages.label_appointment3}" />
				</h:outputFormat>
				<p:dataTable id="list" value="#{appointmentBean.allAppointments}"
					var="appointment"
					filteredValue="#{appointmentBean.filteredAppointments}"
					rendered="#{appointmentBean.dataVisible}" resizableColumns="false"
					paginator="true" emptyMessage="#{messages.label_no_records_found}"
					paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown} "
					rowsPerPageTemplate="5,10,25,50" rows="10">


					<ui:insert name="appointmentTableFields">
						<ui:include src="fieldsPages/appointmentTableFields.xhtml" />
					</ui:insert>

					<p:column styleClass="action-column" exportable="false">
						<f:facet name="header">
							<h:outputText value="#{messages.label_actions}" />
						</f:facet>
						<p:commandButton id="viewButton" icon="ui-icon-zoomin"
							update=":viewForm:viewPanelGrid"
							oncomplete="PF('viewDialogWidget').show()"
							title="#{messages.label_view}">
							<f:setPropertyActionListener value="#{appointment}"
								target="#{appointmentBean.appointment}" />
						</p:commandButton>
						<p:tooltip for="viewButton" value="#{messages.label_view}"
							showEffect="fade" hideEffect="fade" />
						<p:commandButton id="editButton" icon="ui-icon-pencil"
							update=":editForm:editPanelGrid"
							action="#{appointmentBean.onEdit}"
							oncomplete="PF('editDialogWidget').show()"
							title="#{messages.label_edit}">
							<f:setPropertyActionListener value="#{appointment}"
								target="#{appointmentBean.appointment}" />
						</p:commandButton>
						<p:tooltip for="editButton" value="#{messages.label_edit}"
							showEffect="fade" hideEffect="fade" />
						<p:commandButton id="deleteButton" icon="ui-icon-trash"
							oncomplete="PF('deleteDialogWidget').show()"
							title="#{messages.label_delete}">
							<f:setPropertyActionListener value="#{appointment}"
								target="#{appointmentBean.appointment}" />
						</p:commandButton>
						<p:tooltip for="deleteButton" value="#{messages.label_delete}"
							showEffect="fade" hideEffect="fade" />

						<p:commandButton action="#{appointmentBean.sendMail}"  id="sendButton" icon="ui-icon-mail-open"
						update=":dataForm:data :growlForm:growl"
							title="#{messages.label_send}">
							<f:setPropertyActionListener value="#{appointment}"
								target="#{appointmentBean.appointment}" />
						</p:commandButton>
						<p:tooltip for="sendButton" value="#{messages.label_send}"
							showEffect="fade" hideEffect="fade" />

					</p:column>
				</p:dataTable>

				<h:commandLink>
					<p:graphicImage library="images" name="excel.png" width="24"
						alt="XLS" />
					<p:dataExporter type="xls" target="list"
						fileName="#{messages.label_appointment3}" />
				</h:commandLink>

				<h:commandLink>
					<p:graphicImage library="images" name="pdf.png" width="24"
						alt="PDF" />
					<p:dataExporter type="pdf" target="list"
						fileName="#{messages.label_appointment3}" />
				</h:commandLink>

			</p:panel>
		</h:form>

		<p:dialog id="createDialog"
			header="#{messages.label_create} #{messages.label_appointment}"
			widgetVar="createDialogWidget" dynamic="true"
			visible="#{appointmentBean.createDialogVisible}" showEffect="fade">
			<p:ajax event="close" update=":dataForm:data"
				listener="#{appointmentBean.handleDialogClose}" />
			<p:outputPanel id="createPanel">
				<h:form id="createForm" enctype="multipart/form-data">
					<h:panelGrid id="createPanelGrid" columns="3" styleClass="dialog"
						columnClasses="col1,col2,col3">

						<ui:insert name="appointmentCreateFields">
							<ui:include src="fieldsPages/appointmentWriteFields.xhtml" />
						</ui:insert>

					</h:panelGrid>
					<p:commandButton id="createSaveButton"
						value="#{messages.label_save}" action="#{appointmentBean.persist}"
						update="createPanelGrid :growlForm:growl :dataForm:data" />
					<p:commandButton id="createCloseButton"
						value="#{messages.label_close}"
						onclick=" PF('createDialogWidget').hide()" type="button" />
				</h:form>
			</p:outputPanel>
		</p:dialog>

		<p:dialog id="editDialog"
			header="#{messages.label_edit} #{messages.label_appointment}"
			widgetVar="editDialogWidget" dynamic="true" maximizable="true"
			showEffect="fade">
			<p:ajax event="close" update=":dataForm:data"
				listener="#{appointmentBean.handleDialogClose}" />
			<p:outputPanel id="editPanel">
				<h:form id="editForm" enctype="multipart/form-data">
					<h:panelGrid id="editPanelGrid" columns="3" styleClass="dialog"
						columnClasses="col1,col2,col3">

						<ui:insert name="appointmentEditFields">
							<ui:include src="fieldsPages/appointmentWriteFields.xhtml" />
						</ui:insert>

					</h:panelGrid>
					<p:commandButton id="editSaveButton" value="#{messages.label_save}"
						action="#{appointmentBean.persist}"
						update="editPanelGrid :growlForm:growl :dataForm:data" />
					<p:commandButton id="editCloseButton"
						value="#{messages.label_close}"
						onclick="PF('editDialogWidget').hide()" type="button" />
				</h:form>
			</p:outputPanel>
		</p:dialog>


		<p:dialog id="viewDialog"
			header="#{messages.label_view} #{messages.label_appointment}"
			widgetVar="viewDialogWidget" dynamic="true" showEffect="fade">
			<p:outputPanel id="viewPanel">
				<h:form id="viewForm" enctype="multipart/form-data">
					<h:panelGrid id="viewPanelGrid" columns="2" styleClass="dialog"
						columnClasses="col1,col2">

						<ui:insert name="appointmentReadFields">
							<ui:include src="fieldsPages/appointmentReadFields.xhtml" />
						</ui:insert>


					</h:panelGrid>
					<p:commandButton id="viewCloseButton"
						value="#{messages.label_close}" onclick="PF('viewDialogWidget').hide()"
						type="button" />
				</h:form>
			</p:outputPanel>
		</p:dialog>

		<p:confirmDialog id="deleteDialog" widgetVar="deleteDialogWidget"
			message="#{messages.label_delete_record}" showEffect="fade"
			header="#{messages.label_confirm_deletion}" severity="alarm">
			<p:outputPanel id="deletePanel">
				<h:form id="deleteForm">
					<p:commandButton id="deleteYesButton" value="#{messages.label_yes}"
						action="#{appointmentBean.delete}"
						update=":dataForm:data :growlForm:growl :dataForm:data"
						oncomplete="PF('deleteDialogWidget').hide()" />
					<p:commandButton id="deleteNoButton" value="#{messages.label_no}"
						onclick="PF('deleteDialogWidget').hide()" type="button" />
				</h:form>
			</p:outputPanel>
		</p:confirmDialog>

	</ui:define>
</ui:composition> </html>

src/main/webapp/pages/secure/main.xhtml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<ui:composition template="../../templates/layout.xhtml">
  <ui:define name="content">
    <p:panel id="mainPanel" toggleable="true" toggleSpeed="250">
      <f:facet name="header">
        <h:outputFormat value="#{messages.label_welcome_titlepane}">
          <f:param value="#{applicationBean.appName}" />
        </h:outputFormat>
      </f:facet>
      <p />
      <h:outputText id="welcomeText" value="#{messages.label_welcome_text}" />
      <p />
      <div id="media"></div>
    </p:panel>
  </ui:define>
</ui:composition>
</html>