src/main/java/com/przychodnia/rejestracja/jsf/BhoursBean.java
package com.przychodnia.rejestracja.jsf;

import com.przychodnia.rejestracja.domain.Bhours;
import com.przychodnia.rejestracja.domain.Doctor;
import com.przychodnia.rejestracja.jsf.util.Day;
import com.przychodnia.rejestracja.jsf.util.Literals;
import com.przychodnia.rejestracja.jsf.util.MessageFactory;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import org.primefaces.event.CloseEvent;
import org.primefaces.event.SelectEvent;
import org.primefaces.event.UnselectEvent;
import org.springframework.beans.factory.annotation.Configurable;

@ManagedBean(name = "bhoursBean")
@SessionScoped
@Configurable
public class BhoursBean implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 7487846715965801488L;
	private String name = "bhours";
	private String dayOfWeekString;
	private Bhours bhours;
	private List<Bhours> allBhourses;
	private List<Bhours> filteredBhourses;
	private List<Bhours> filteredBhoursesForDoctor;
	private Doctor selectedDoctor;
	private boolean dataVisible = false;
	private boolean createDialogVisible = false;

	@PostConstruct
	public void init() {
		findAllBhourses();
		DoctorBean.findAllDoctors();
		bhours = new Bhours();
	}

	// Wyswietlanie
	public String findAllBhourses() {
		allBhourses = Bhours.findAllBhourses();
		dataVisible = !allBhourses.isEmpty();
		return null;
	}
	
	public String findBhoursForDoctor(Doctor doctor) {
		filteredBhoursesForDoctor = Bhours.findBhoursesByDoctor(doctor);
		return null;
	}

	//Obsluga listenrow
	  public void onRowSelect(SelectEvent event) {
		  findBhoursForDoctor(getSelectedDoctor());
		  
		  FacesMessage facesMessage = MessageFactory.getMessage("doctor_selected",((Doctor) event.getObject()).getSurname());		
			FacesContext.getCurrentInstance().addMessage(null, facesMessage);
	    }
	 
	    public void onRowUnselect(UnselectEvent event) {
	    	FacesMessage facesMessage = MessageFactory.getMessage("doctor_unselected",((Doctor) event.getObject()).getSurname());		
			FacesContext.getCurrentInstance().addMessage(null, facesMessage);
	    }
	    
	public String displayList() {
		createDialogVisible = false;
		findAllBhourses();
		return "bhours";
	}

	public String displayOfficeHours() {
		return "bhours";
	}

	public String displayCreateDialog() {
		bhours = new Bhours();
		createDialogVisible = true;
		return "bhours";
	}

	// Zapisywanie
	public void persist() {
		String message = "";
		if (!bhours.isBhoursTaken()) {
			
		if (bhours.getId() != null) {
				bhours.merge();
				message = "message_successfully_updated";
			} else {
				bhours.persist();
				message = "message_successfully_created";
			}
			FacesMessage facesMessage = MessageFactory.getMessage(message,
					Literals.BHOURS);
			FacesContext.getCurrentInstance().addMessage(null, facesMessage);
			findBhoursForDoctor(bhours.getDoctor());
			reset();
		}
		else {
			
			FacesMessage facesMessage = MessageFactory.getMessage("bhours_notsucesfully_added_reason");		
			FacesContext.getCurrentInstance().addMessage(null, facesMessage);
			
		findBhoursForDoctor(bhours.getDoctor());
		reset();
		}
	}

	// Usuwanie
	public void delete() {
		bhours.remove();
		FacesMessage facesMessage = MessageFactory
				.getMessage("message_successfully_deleted");
		FacesContext.getCurrentInstance().addMessage(null, facesMessage);
		findBhoursForDoctor(bhours.getDoctor());
		reset();
	}

	// Util
	public void reset() {
		bhours = null;
		createDialogVisible = false;
	}

	public void handleDialogClose(CloseEvent event) {
		reset();
	}

	// Gettery i settery
	public boolean isDataVisible() {
		return dataVisible;
	}

	public void setDataVisible(boolean dataVisible) {
		this.dataVisible = dataVisible;
	}

	public Bhours getBhours() {
		if (bhours == null) {
			bhours = new Bhours();
		}
		return bhours;
	}

	public void setBhours(Bhours bhours) {
		this.bhours = bhours;
	}

	public Day[] getDays() {
		return Day.values();
	}

	public String onEdit() {
		return null;
	}

	public boolean isCreateDialogVisible() {
		return createDialogVisible;
	}

	public void setCreateDialogVisible(boolean createDialogVisible) {
		this.createDialogVisible = createDialogVisible;
	}

	public String getName() {
		return name;
	}

	public Doctor getSelectedDoctor() {
				return selectedDoctor;
	}

	public void setSelectedDoctor(Doctor selectedDoctor) {
		this.selectedDoctor = selectedDoctor;
	}

	public List<Bhours> getAllBhourses() {
		return allBhourses;
	}

	public void setAllBhourses(List<Bhours> allBhourses) {
		this.allBhourses = allBhourses;
	}

	public List<Bhours> getFilteredBhourses() {
		return filteredBhourses;
	}

	public void setFilteredBhourses(List<Bhours> filteredBhourses) {
		this.filteredBhourses = filteredBhourses;
	}

	public List<Bhours> getFilteredBhoursesForDoctor() {
		return filteredBhoursesForDoctor;
	}

	public void setFilteredBhoursesForDoctor(List<Bhours> filteredBhoursesForDoctor) {
		this.filteredBhoursesForDoctor = filteredBhoursesForDoctor;
	}

	public String getDayOfWeekString() {
		return dayOfWeekString;
	}

	public void setDayOfWeekString(String dayOfWeekString) {
		this.dayOfWeekString = dayOfWeekString;
	}
}

src/main/webapp/pages/secure/fieldsPages/appointmentReadFields.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"> <ui:composition>
	
<p:outputLabel value="#{messages.label_appointmentdetails}"
							for="appointmentdetails" />
						<h:outputText id="appointmentdetails"
							value="#{appointmentBean.appointment.appointmentDetails}" />

						<h:outputLabel for="patientInput"
							value="#{messages.label_patient2}" />
						<h:outputText id="patientInput"
							value="#{appointmentBean.appointment.patient.toStringNameAndSurname()}" />

						<h:outputLabel for="doctorInput" value="#{messages.label_doctor2}" />
						<h:outputText id="doctorInput"
							value="#{appointmentBean.appointment.doctor.toStringNameAndSurname()}" />

						<p:outputLabel value="#{messages.label_appointmentstartDate}"
							for="appointmentstartdate" />
							<h:outputText id="appointmentstartdate" value="#{appointmentBean.appointment.appointmentStartDate}">
							<f:convertDateTime pattern="dd.MM.YYYY HH:mm" />
							
						</h:outputText>

						<p:outputLabel value="#{messages.label_appointmentEndtDate}"
							for="appointmentenddate" />
							<h:outputText id="appointmentenddate" value="#{appointmentBean.appointment.appointmentEndtDate}">
							<f:convertDateTime pattern="dd.MM.YYYY HH:mm" />
						</h:outputText>

</ui:composition> </html>

src/main/webapp/pages/secure/fieldsPages/appointmentTableFields.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"> <ui:composition>
	
	<p:column filterBy="#{appointment.appointmentDetails}"
						sortBy="#{appointment.appointmentDetails}"
						filterMatchMode="contains"
						headerText="#{messages.label_appointmentdetails}">
						<h:outputText value="#{appointment.appointmentDetails}" />
					</p:column>

					<p:column headerText="#{messages.label_appointmentstartDate}"
						filterBy="#{appointment.appointmentStartDate}"
						sortBy="#{appointment.appointmentStartDate}"
						filterMatchMode="contains">
						<h:outputText value="#{appointment.appointmentStartDate}">
							<f:convertDateTime pattern="dd.MM.YYYY HH:mm" />
						</h:outputText>
					</p:column>

					<p:column headerText="#{messages.label_appointmentEndtDate}"
						filterBy="#{appointment.appointmentEndtDate}"
						sortBy="#{appointment.appointmentEndtDate}"
						filterMatchMode="contains">
						<h:outputText value="#{appointment.appointmentEndtDate}">
							<f:convertDateTime pattern="dd.MM.YYYY HH:mm" />
						</h:outputText>
					</p:column>

					<p:column headerText="#{messages.label_doctor2}"
						filterBy="#{appointment.doctor.surname}"
						sortBy="#{appointment.doctor.surname}" filterMatchMode="contains">
						<h:outputText value="#{appointment.doctor.surname}" />
					</p:column>

					<p:column headerText="#{messages.label_patient2}"
						filterBy="#{appointment.patient.surname}"
						sortBy="#{appointment.patient.surname}" filterMatchMode="contains">
						<h:outputText value="#{appointment.patient.surname}" />
					</p:column>

</ui:composition> </html>

src/main/webapp/pages/secure/fieldsPages/appointmentWriteFields.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"> <ui:composition>

	<p:outputLabel value="#{messages.label_appointmentdetails}"
		for="appointmentdetails" />
	<p:inputText id="appointmentdetails"
		value="#{appointmentBean.appointment.appointmentDetails}"
		required="true" requiredMessage="#{messages.required}">
		<p:clientValidator event="keyup" />
		<f:validateLength minimum="3" maximum="20" />
	</p:inputText>
	<p:message for="appointmentdetails" />

	<h:outputLabel for="patientInput" value="#{messages.label_patient2}" />
	<p:autoComplete id="patientInput"
		value="#{appointmentBean.appointment.patient}" var="pat"
		itemLabel="#{pat.surname} #{pat.firstName}"
		emptyMessage="#{messages.label_no_records_found}"
		placeholder="#{messages.label_patient2}" 
		converter="personConverter" itemValue="#{pat}"
		completeMethod="#{appointmentBean.completePatient}" 
		required="true" requiredMessage="#{messages.required}">
		<p:clientValidator event="keyup" />
	</p:autoComplete>
	<p:message for="patientInput" />

	<h:outputLabel for="doctorInput" value="#{messages.label_doctor2}" />
	<p:autoComplete id="doctorInput"
		value="#{appointmentBean.appointment.doctor}" var="doc"
		completeMethod="#{appointmentBean.completeDoctor}" 
		itemLabel="#{doc.surname} #{doc.firstName}"
		emptyMessage="#{messages.label_no_records_found}"
		placeholder="#{messages.label_doctor2}"  converter="doctorConverter"
		itemValue="#{doc}" required="true"
		requiredMessage="#{messages.required}">
		<p:clientValidator event="keyup" />

		<p:ajax event="itemSelect" listener="#{scheduleBean.onDoctorSelect}"
			update=":growlForm:growl" />
	</p:autoComplete>
	<p:message for="doctorInput" />

	<p:outputLabel value="#{messages.label_appointmentstartDate}"
		for="appointmentstartdate" />
	<p:calendar id="appointmentstartdate"
		value="#{appointmentBean.appointment.appointmentStartDate}"
		pattern="dd-MM-yyyy HH:mm" mask="true" required="true"
		requiredMessage="#{messages.required}">
		<p:ajax event="dateSelect" update="appointmentenddate" />
	</p:calendar>
	<p:message for="appointmentstartdate" />

	<p:outputLabel value="#{messages.label_appointmentEndtDate}"
		for="appointmentenddate" />
	<p:calendar id="appointmentenddate"
		mindate="#{appointmentBean.appointment.appointmentStartDate}"
		value="#{appointmentBean.appointment.appointmentEndtDate}"
		pattern="dd-MM-yyyy HH:mm" mask="true" required="true"
		requiredMessage="#{messages.required}">
		<f:attribute name="startDate"
			value="#{appointmentBean.appointment.appointmentStartDate}" />
		<f:validator validatorId="custom.dateRangeValidator" />
	</p:calendar>
	<p:message for="appointmentenddate" />
</ui:composition> </html>

src/main/webapp/pages/secure/fieldsPages/bhoursReadFields.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
		xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"> <ui:composition>
	
	<p:column headerText="Lekarz" filterBy="#{bhours.doctor.surname}" rendered="false"
						sortBy="#{bhours.doctor.surname}" filterMatchMode="startsWith">
						<h:outputText value="#{bhours.doctor.surname}" rendered="false"/>
					</p:column>

					<p:column headerText="Dzień tygodnia" filterBy="#{bhours.weekDay}" 
						sortBy="#{bhours.weekDay}" filterMatchMode="startsWith">
						<h:outputText value="#{bhours.weekDay}"
							converter="dayOfWeekConverter" />
					</p:column>

					<p:column headerText="Od godziny" filterBy="#{bhours.open_time}"
						sortBy="#{bhours.open_time}" filterMatchMode="contains">
						<h:outputText value="#{bhours.open_time}">
							<f:convertDateTime pattern="HH:mm" />
						</h:outputText>
					</p:column>

					<p:column headerText="Do godziny" filterBy="#{bhours.close_time}"
						sortBy="#{bhours.close_time}" filterMatchMode="contains">
						<h:outputText value="#{bhours.close_time}">
							<f:convertDateTime pattern="HH:mm" />
						</h:outputText>
					</p:column>

</ui:composition> </html>

src/main/webapp/pages/secure/fieldsPages/bhoursWriteFields.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:p="http://primefaces.org/ui">
<ui:composition>

	<p:outputLabel for="doctorInput" value="#{messages.label_doctor2}" />
	<p:autoComplete id="doctorInput" value="#{bhoursBean.bhours.doctor}"
		var="doc" completeMethod="#{appointmentBean.completeDoctor}"
		itemLabel="#{doc.surname} #{doc.firstName}" forceSelection="true"
		emptyMessage="#{messages.label_no_records_found}" required="true"
		requiredMessage="#{messages.required}"
		placeholder="#{messages.label_doctor2}" converter="doctorConverter"
		itemValue="#{doc}" dropdown="true">
	</p:autoComplete>
	<p:message for="doctorInput" />

	<p:outputLabel for="dayOfWeekInput" value="#{messages.label_dayOfWeek}" />
	<p:selectOneMenu id="dayOfWeekInput" required="true"
		requiredMessage="#{messages.required}"
		value="#{bhoursBean.bhours.weekDay}" style="width:100%">
		<f:selectItems value="#{bhoursBean.days}" var="day"
			itemLabel="#{day.local}" itemValue="#{day.value}" />
	</p:selectOneMenu>
	<p:message for="dayOfWeekInput" />

	<p:outputLabel for="startTime" value="#{messages.label_from}" />
	<pe:timePicker id="startTime" value="#{bhoursBean.bhours.open_time}"
		mode="popup" widgetVar="startTimeWidget" locale="pl" required="true"
		onHourShow="tpStartOnHourShowCallback"
		onMinuteShow="tpStartOnMinuteShowCallback"
		requiredMessage="#{messages.required}" />
	<p:message for="startTime" />
	
	<p:outputLabel for="endTime"
		value="#{messages.label_appointmentEndtDate}" />
	<pe:timePicker id="endTime" value="#{bhoursBean.bhours.close_time}"
		mode="popup" widgetVar="endTimeWidget" locale="pl" required="true"
		onHourShow="tpEndOnHourShowCallback"
		onMinuteShow="tpEndOnMinuteShowCallback"
		requiredMessage="#{messages.required}" />
	<p:message for="endTime" />

</ui:composition>
</html>

src/main/webapp/pages/secure/fieldsPages/doctorReadFields.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"> <ui:composition>
	
	<p:outputLabel value="#{messages.label_surname}" for="surname" />
	<h:outputText id="surname" value="#{doctorBean.doctor.surname}" />
	
	<p:outputLabel value="#{messages.label_name}" for="firstName" />
	<h:outputText id="firstName" value="#{doctorBean.doctor.firstName}" />

	<p:outputLabel value="#{messages.label_profession}" for="profession" />
	<h:outputText id="profession" value="#{doctorBean.doctor.profession}" />

	<p:outputLabel value="#{messages.labe_doctorpatientslist}"
		for="doctorpatientslist" />

	<p:dataList id="doctorpatientslist"
		value="#{doctorBean.getPatientList()}" var="pat" dropdown="true">
       					 #{pat.firstName} #{pat.surname}
  						  </p:dataList>

</ui:composition> </html>

src/main/webapp/pages/secure/fieldsPages/doctorTableReadFields.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"> <ui:composition>

	<p:column filterBy="#{doctor.firstName}" sortBy="#{doctor.firstName}"
		filterMatchMode="contains">
		<f:facet name="header">
			<h:outputText value="#{messages.label_name}" />
		</f:facet>
		<h:outputText value="#{doctor.firstName}" />
	</p:column>

	<p:column filterBy="#{doctor.surname}" sortBy="#{doctor.surname}"
		filterMatchMode="contains">
		<f:facet name="header">
			<h:outputText value="#{messages.label_surname}" />
		</f:facet>
		<h:outputText value="#{doctor.surname}" />
	</p:column>

	<p:column filterBy="#{doctor.profession}" sortBy="#{doctor.profession}"
		filterMatchMode="contains">
		<f:facet name="header">
			<h:outputText value="#{messages.label_profession}" />
		</f:facet>
		<h:outputText value="#{doctor.profession}" />
	</p:column>

</ui:composition> </html>

src/main/webapp/pages/secure/fieldsPages/doctorWriteFields.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"> 
	<ui:composition>


<p:outputLabel value="#{messages.label_name}" for="firstname" />
	<p:inputText id="firstname" value="#{doctorBean.doctor.firstName}"
		required="true" requiredMessage="#{messages.required}">
		<p:clientValidator event="keyup" />
		<f:validateLength minimum="3" maximum="20" />
	</p:inputText>
	<p:message for="firstname" />

	<p:outputLabel value="#{messages.label_surname}" for="surname" />
	<p:inputText id="surname" value="#{doctorBean.doctor.surname}"
		required="true" requiredMessage="#{messages.required}">
		<p:clientValidator event="keyup" />
		<f:validateLength minimum="3" maximum="20" />
	</p:inputText>
	<p:message for="surname" />

	<p:outputLabel value="#{messages.label_profession}" for="profession" />
	<p:inputText id="profession" value="#{doctorBean.doctor.profession}"
		required="true" requiredMessage="#{messages.required}">
		<p:clientValidator event="keyup" />
		<f:validateLength minimum="3" maximum="20" />
	</p:inputText>
	<p:message for="profession" />

</ui:composition> </html>

src/main/webapp/pages/secure/fieldsPages/mailReadFields.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"> 
	<ui:composition>

<p:outputLabel value="#{messages.label_subject}" for="subject" />
	<h:outputText id="subject" value="#{mailBean.mail.subject}"
		required="true" requiredMessage="#{messages.required}">
	</h:outputText>
<!-- 	<p:message for="subject" /> -->

	<p:outputLabel value="#{messages.label_body}" for="body" />
	<h:outputText id="body" value="#{mailBean.mail.body}"
		required="true" requiredMessage="#{messages.required}">
	</h:outputText>
<!-- 	<p:message for="body" /> -->

	<p:outputLabel value="#{messages.label_date}" for="date" />
	<h:outputText id="date" value="#{mailBean.mail.dateMail}"
		required="true" requiredMessage="#{messages.required}">
		 <f:convertDateTime timeStyle="short" pattern="EEE, dd/MM/YYYY HH:mm" type="both" />
	</h:outputText>
<!-- 	<p:message for="date" /> -->
	
		<p:outputLabel value="#{messages.label_appointment}" for="appointment" />
	<h:outputText id="appointment" value="#{mailBean.mail.appointment.toStringAppointment()}"
		required="true" requiredMessage="#{messages.required}">
	</h:outputText>
<!-- 	<p:message for="appointment" /> -->
	
	<p:outputLabel value="#{messages.label_send}" for="send" />
	<h:outputText id="send" value="#{mailBean.mail.send}"
		required="true" requiredMessage="#{messages.required}">
	</h:outputText>

<p:outputLabel value="#{messages.label_description}" for="description" />
	<h:outputText id="description" value="#{mailBean.mail.description}"
		required="true" requiredMessage="#{messages.required}">
	</h:outputText>
	


</ui:composition> </html>

src/main/webapp/pages/secure/fieldsPages/mailTableReadFields.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"> <ui:composition>

	<p:column filterBy="#{mail.subject}" sortBy="#{mail.subject}"
		filterMatchMode="contains">
		<f:facet name="header">
			<h:outputText value="#{messages.label_subject}" />
		</f:facet>
		<h:outputText value="#{mail.subject}" />
	</p:column>

	<p:column filterBy="#{mail.body}" sortBy="#{mail.body}"
		filterMatchMode="contains">
		<f:facet name="header">
			<h:outputText value="#{messages.label_body}" />
		</f:facet>
		<h:outputText value="#{mail.body}" />
	</p:column>

		<p:column filterBy="#{mail.dateMail}" sortBy="#{mail.dateMail}"
		filterMatchMode="contains">
		<f:facet name="header">
			<h:outputText value="#{messages.label_date}" />
		</f:facet>
		<h:outputText value="#{mail.dateMail}" >
		 <f:convertDateTime pattern="dd.MM.YYYY HH:mm" />
		  </h:outputText>
	</p:column>
	
		<p:column filterBy="#{mail.appointment}" sortBy="#{mail.appointment}"
		filterMatchMode="contains">
		<f:facet name="header">
			<h:outputText value="#{messages.label_appointment}" />
		</f:facet>
		<h:outputText value="#{mail.appointment.toStringAppointment()}" />
	</p:column>
	
	<p:column filterBy="#{mail.send}" sortBy="#{mail.send}"
		filterMatchMode="contains">
		<f:facet name="header">
			<h:outputText value="#{messages.label_send}" />
		</f:facet>
		<h:outputText value="#{mail.send}" />
	</p:column>
	
	<p:column filterBy="#{mail.description}" sortBy="#{mail.description}"
		filterMatchMode="contains">
		<f:facet name="header">
			<h:outputText value="#{messages.label_description}" />
		</f:facet>
		<h:outputText value="#{mail.description}" />
	</p:column>

</ui:composition> </html>